### ISSUE TITLE
draw user background

### ISSUE THREAD

**Issue by aaditya4u** [linuxmint/doc-troubleshooting-guide#14]
"**draw user background=ture**" is not working. it works with all default backounds which has provided by OShowever, when we choose own background it takes deault mint bg as lockscreen and login screen. 

how to update lightdm or where is issue? please help.

**Comment by xenopeek** [comment]
This is not an issue about the troubleshooting guide so closing this here. For help with Linux Mint issues and questions please ask on the support forums: https://forums.linuxmint.com/
