### ISSUE TITLE
WIFI does not work if transmission channel is 12 or 13

### ISSUE THREAD

**Issue by CCH38** [linuxmint/doc-troubleshooting-guide#20]
**Linux Cinnamon 21.1 64 bits** : I set my internet freebox with an automatic choice of the transmission channel. Then, if the freebox chooses the channel 12 or 13, the WIFI of my freebox is not seen by the PC and the WIFI cannot work.

**Comment by xenopeek** [comment]
This project is for the troubleshooting guide, not for help with Linux Mint problems. You can use any of the support channels for that, like the Networking forum https://forums.linuxmint.com/viewforum.php?f=52.
