### ISSUE TITLE
Mint 20.3 Cinnamon Does not Reconnect on Ethernet After Sleep

### ISSUE THREAD

**Issue by maciekskontakt** [linuxmint/doc-troubleshooting-guide#22]
This is on hardware ASUS PN50 (AMD). Ethernet built-in. After sleep it does not reconnect when Linux is woken up. No manual forcing helps, occasionally reconnecting cable may help but not always. Only system restart helps reliably. This does not occur when using USB Ethernet dongle. So it looks like driver for builtin hardware in ASUS barebone does not behave correctly or it does not use proper sequence of operations to re-connect to router. The same router works with newer Mint version even on old legacy hardware (MacBook Air from 2011) via USB dongle with no issues. The router works with about 20 devices and 6 computers on different OS's so, this should not be an issue related to router, but this particular Mint version with it's updates.

It worked perfectly when installed in 2022  and it does not now. Linux Mint 20.3 (5.2.7) Cinnamon after many kernel updates by software update through update manager. Kernel is 5.4.0-170-generic.

**Comment by xenopeek** [comment]
This project is for the troubleshooting guide, not for help with Linux Mint problems. You can use any of the support channels for that, like the Networking forum https://forums.linuxmint.com/viewforum.php?f=52.

**Comment by maciekskontakt** [comment]
I am not looking for help with troubleshooting but for fix. Where do I report problems? On forums???
Thanks,-Maciek

    On Friday, January 26, 2024 at 12:37:23 PM EST, xenopeek ***@***.***> wrote:  
 
 


This project is for the troubleshooting guide, not for help with Linux Mint problems. You can use any of the support channels for that, like the Networking forum https://forums.linuxmint.com/viewforum.php?f=52.
